#pragma once
#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <netinet/in.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/epoll.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>

#include <string>
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <map>
#include <memory>
#include "10_Config.hpp"
#include "11_Server.hpp"
#include "12_Location.hpp"
#include "12-1_LocationAPI.hpp"
#include "12-2_LocationDownload.hpp"
#include "12-3_LocationUpload.hpp"
#include "12-4_LocationCGI.hpp"
#include "13_FileParser.hpp"

#include "00_ServerManager.hpp"